/*
mech Mod
Author: Peter Roohr
Date: 01/26/2018
overview: master header file for all hud functions across all mechs
*/

string HUD_BLK_IMG_B;
string HUD_MTK_IMG_B;
string HUD_MNT_IMG_B;

//-------------------------BALAKET------------------------
void() hud_blk_frame;

//-------------------------MATOK------------------------
void() hud_mtk_frame;

//-------------------------MONITOR------------------------
void() hud_mnt_frame;
