/*
battleMETAL
Author: Peter Roohr
Date: 10/12/2016
Overview: csqc defs for main game
*/


//STAT FIELD VARS

.float stat_legs_hp;  //TODO - delete, deprecated
.float stat_ctor_hp;  //TODO - delete, deprecated
.float stat_ltor_hp;  //TODO - delete, deprecated
.float stat_rtor_hp;  //TODO - delete, deprecated
.float stat_larm_hp;  //TODO - delete, deprecated
.float stat_rarm_hp;  //TODO - delete, deprecated
